### PR TITLE
Added extra info about styling Page

### PR DESCRIPTION
**Pull request by lukeramsden**

### CODE REVIEW

**Comment by NathanaelA** [comment]
@lukeramsden - Thanks for the pull request; but I don't understand the point to that text.  The idea behind this plugin is to `automatically` add the .ios / .android to the Page tag so that your CSS will work per platform.      

You don't want to hard code .ios or .android on all your pages as then when you run it on the other platform it will have the wrong platfrom.  :grinning:

In addition it now adds the .iosX / .androidX where X is the width, to allow customizations based on the screen size.

**Comment by lukeramsden** [comment]
@NathanaelA I was trying to say that if you want to style the Page tag, `.ios Page {}` doesn't work, you have to do `.ios {}` instead. Also, I do because I wanted a light grey on android and white on iOS.

**Comment by lukeramsden** [comment]
@NathanaelA Changed it slightly

**Comment by NathanaelA** [comment]
Unless you were trying to say that if you want to style your Page css in css; then you are correct you can use `Page.ios` or `Page.android` would be the recommended way so you know it is for the Page element.  :grinning:

**Comment by lukeramsden** [comment]
@NathanaelA Ahhhhhh..... That worked 😂😂 Turns out I was doing Page .android instead of Page.android.... Nevermind then. Stupid whitespace.

**Comment by NathanaelA** [comment]
Yeah, on the root element that "space" can kill you.  Though if you want to do a PR to update the docs to state that, I would merge it.  :grinning:    If not, I'll add it to my side and then the next time I do an upgrade to the stuff I'll push it.  😀

**Comment by lukeramsden** [comment]
@NathanaelA Just do it on your side :)

**Pull request closed without merging**
