### PR TITLE
Updated to NS 3.0.0

### PR DESCRIPTION
**Pull request by lukeramsden**
Solves #4 

Ignore the weird commits (just squash merge), I committed to the wrong branch :P

### CODE REVIEW

**Comment by lukeramsden** [comment]
@NathanaelA Could this be merged and released?

**Comment by NathanaelA** [comment]
Sorry, you committed this while I was sorta on vacation (away from computer).   I am in the process of catching up with all my paid work; after that point I will be going through the different pull requests that people have left on my free plugins and testing them to verify that all the functionality still works under 3.0.    

This pull request looks fairly simple; so I think it should work; but I hate buggy plugins; so I need to test it first.  😀

**Comment by lukeramsden** [comment]
@NathanaelA No problem, was just wondering what was going on :)

**Comment by NathanaelA** [comment]
v1.6 was released today which I know for sure has this patch.

**Pull request closed without merging**
